config/routes.rb
Rails.application.routes.draw do

  resources :res_mesas
  resources :llamadas
  resources :tandas do
    match :cierra, via: :get, on: :member
    match :recupera, via: :get, on: :member
  end
  resources :reservaciones
  resources :detalle_reservas
  resources :mesas do 
    match :reservar, via: :get, on: :member
  end
  resources :cierres
  resources :reservas do
    match :confirmacion, via: :get, on: :member
    match :reservas_cerradas, via: :get, on: :member
    match :reservacion, via: :get, on: :collection
    match :dia_reserva, via: :get, on: :collection
    match :elige_dia, via: :post, on: :collection
    match :anula, via: :get, on: :member
    match :recupera, via: :get, on: :member
    match :asigna_mesa, via: :get, on: :member
    match :elimina_mesa, via: :get, on: :member
  end
  resources :items
  resources :grupos do
    resources :items
  end
  resources :areas
  resources :proyectos do
    resources :areas
  end
  scope module: 'aplicacion' do
    resources :app_administradores
    resources :app_nominas
    resources :app_perfiles do
      # recurso SOLO si hay manejo de ESTADOS
      resources :st_perfil_modelos
      match :desvincular, via: :get, on: :member
    end
    resources :app_observaciones
    resources :app_mejoras

    resources :app_recursos do
      collection do
        match :ayuda, via: :get
        match :home, via: :get
        match :administracion, via: :get
        match :procesos, via: :get
      end
    end

    resources :app_imagenes
    resources :app_contactos
    resources :app_mensajes do
      match :respuesta, via: :post, on: :collection
      match :estado, via: :get, on: :member
    end
    resources :app_msg_msgs

    resources :app_documentos
    resources :app_dir_dires
    resources :app_directorios do
      match :nuevo, via: :post, on: :collection
    end
    resources :app_repos do
      match :publico, via: :get, on: :collection
      match :perfil, via: :get, on: :collection
    end
    resources :app_archivos

    resources :app_enlaces

  end

  scope module: 'home' do
    resources :h_imagenes
    resources :h_links
    resources :h_temas
  end
  
  scope module: 'sidebar' do
    resources :sb_elementos
    resources :sb_listas do
      resources :sb_elementos
    end
  end


  # SCOPE HELP
  scope module: 'help' do
    resources :hlp_pasos
    resources :hlp_tutoriales do
      resources :hlp_pasos
    end

#    resources :conversaciones
    resources :mensajes do 
      match :estado, via: :get, on: :member
      match :respuesta, via: :post, on: :collection
    end
    resources :pasos
    resources :tema_ayudas do
      resources :tutoriales
    end
    resources :tutoriales do
      resources :pasos
    end
  end

  scope module: 'estados' do
    resources :st_estados do
      match :asigna, via: :get, on: :member
    end
    resources :st_modelos do 
      resources :st_estados
      match :asigna, via: :get, on: :member
    end
    resources :st_perfil_estados do
      match :desasignar, via: :get, on: :member
      match :cambia_rol, via: :get, on: :member
    end
    resources :st_perfil_modelos do
      resources :st_perfil_estados
      match :desasignar, via: :get, on: :member
      match :cambia_rol, via: :get, on: :member
      match :cambia_ingreso, via: :get, on: :member
    end
    resources :st_bandejas
  end

  devise_for :usuarios

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'aplicacion/app_recursos#home'

end

app/models/llamada.rb
class Llamada < ApplicationRecord
end

app/controllers/llamadas_controller.rb
class LlamadasController < ApplicationController
  before_action :set_llamada, only: %i[ show edit update destroy ]

  # GET /llamadas or /llamadas.json
  def index
    @coleccion = Llamada.all
  end

  # GET /llamadas/1 or /llamadas/1.json
  def show
  end

  # GET /llamadas/new
  def new
    # Hay que pasar la fecha
    @fecha = Date.parse(params[:d])

    @objeto = Llamada.new(fecha: @fecha)

    @domingo = (@fecha.strftime("%A") == 'Sunday')
    tandas = (@domingo ? Tanda.where(turno: 'Almuerzo') : Tanda.all)

    # Se deben cargar los horarios de un día en particular
    @horarios = tandas.map {|tan| tan.horario.split('-')[0] if abierto(@fecha, tan.horario) }.compact.sort!

  end

  # GET /llamadas/1/edit
  def edit
  end

  # POST /llamadas or /llamadas.json
  def create
    @objeto = Llamada.new(llamada_params)

    respond_to do |format|
      if @objeto.save
        format.html { redirect_to @objeto, notice: "Llamada was successfully created." }
        format.json { render :show, status: :created, location: @objeto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @objeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /llamadas/1 or /llamadas/1.json
  def update
    respond_to do |format|
      if @objeto.update(llamada_params)
        format.html { redirect_to @objeto, notice: "Llamada was successfully updated." }
        format.json { render :show, status: :ok, location: @objeto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @objeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /llamadas/1 or /llamadas/1.json
  def destroy
    @objeto.destroy
    respond_to do |format|
      format.html { redirect_to llamadas_url, notice: "Llamada was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def abierto(fecha, horario)

      ids_dia = Llamada.all.map {|lla| lla.id if lla.fecha.to_date == @fecha}.compact
      llamadas_dia = Llamada.where(id: ids_dia)

      tanda = Tanda.find_by(horario: horario)

      desde = horario.split('-')[0]
      hasta = horario.split('-')[1]

      lla_ids = llamadas_dia.all.map {|lla| lla.id if (lla.hora >= desde and lla.hora < hasta)}.compact
      reservadas = (lla_ids.empty? ? 0 : Llamada.where(id: lla_ids).map {|lla| lla.n_personas.to_i}.sum)
      tanda.capacidad > reservadas
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_llamada
      @objeto = Llamada.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def llamada_params
      params.require(:llamada).permit(:anombre, :contacto, :hora, :paxs, :anulada, :fecha)
    end
end

app/helpers/llamadas_helper.rb
module LlamadasHelper
end

app/views/llamadas/_detail.html.erb
<h3><%= @objeto.fecha %></h3>
<h5 class='text-center text-muted'>LUNES CERRADO</h5>
<h5 class='text-center text-muted'><b>martes a sábado</b> 13:00 a 16:00 - 19:00 a 22:00</br><b>domingo</b> 13:00 a 16:00</h5>
<h5 class='text-center text-muted'>PARA RESERVAS DE MÁS DE 6 PERSONAS O EN HORARIOS ESPECIALES</h5>
<h5 class='text-center text-muted'>POR FAVOR COMINCARSE AL</h5>
<h6 class='text-center text-muted'>Teléfono o WhatsApp +56 9 9613 0353</h6>

<%= render partial: '0p/display/form_fields', locals: {form: form, helper_name: 'text', token: :anombre, label: 'Reserva a nombre de', v: true } %>
<div class='row'>
	<div class='col-md-6'>
		<div class='row'>
			<div class='col-md-6'>
				<%= render partial: '0p/display/form_fields', locals: {form: form, helper_name: 'select', token: :n_personas, label: 'Número de personas', sel_list: Reserva::MESAS, v: true } %>
			</div>
			<div class='col-md-6'>
				<%= render partial: '0p/display/form_fields', locals: {form: form, helper_name: 'select', token: :hora, label: 'Hora de la Reserva', sel_list: @horarios, v: true } %>
			</div>
		</div>
	</div>
	<div class='col-md-6'></div>
</div>

<%= render partial: '0p/display/form_fields', locals: {form: form, helper_name: 'text', token: :n_contacto, label: 'Número telefónico de contacto', v: true } %>

<%= render partial: '0p/display/form_fields', locals: {form: form, helper_name: 'hidden', token: :fecha, label: nil, v: nil } %>

app/views/llamadas/_form.html.erb
<%= form_with(model: llamada, local: true) do |form| %>
  <% if llamada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(llamada.errors.count, "error") %> prohibited this llamada from being saved:</h2>

      <ul>
      <% llamada.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :anombre %>
    <%= form.text_field :anombre %>
  </div>

  <div class="field">
    <%= form.label :contacto %>
    <%= form.text_field :contacto %>
  </div>

  <div class="field">
    <%= form.label :hora %>
    <%= form.text_field :hora %>
  </div>

  <div class="field">
    <%= form.label :paxs %>
    <%= form.number_field :paxs %>
  </div>

  <div class="field">
    <%= form.label :anulada %>
    <%= form.check_box :anulada %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/llamadas/edit.html.erb
<%= render partial: '0p/form/form' %>

app/views/llamadas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Llamadas</h1>

<table>
  <thead>
    <tr>
      <th>Anombre</th>
      <th>Contacto</th>
      <th>Hora</th>
      <th>Paxs</th>
      <th>Anulada</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @llamadas.each do |llamada| %>
      <tr>
        <td><%= llamada.anombre %></td>
        <td><%= llamada.contacto %></td>
        <td><%= llamada.hora %></td>
        <td><%= llamada.paxs %></td>
        <td><%= llamada.anulada %></td>
        <td><%= link_to 'Show', llamada %></td>
        <td><%= link_to 'Edit', edit_llamada_path(llamada) %></td>
        <td><%= link_to 'Destroy', llamada, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Llamada', new_llamada_path %>

app/views/llamadas/new.html.erb
<%= render partial: '0p/form/form' %>

app/views/llamadas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Anombre:</strong>
  <%= @llamada.anombre %>
</p>

<p>
  <strong>Contacto:</strong>
  <%= @llamada.contacto %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @llamada.hora %>
</p>

<p>
  <strong>Paxs:</strong>
  <%= @llamada.paxs %>
</p>

<p>
  <strong>Anulada:</strong>
  <%= @llamada.anulada %>
</p>

<%= link_to 'Edit', edit_llamada_path(@llamada) %> |
<%= link_to 'Back', llamadas_path %>